name: Build deb package
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: matrix.os
    strategy:
      matrix:
        os: [ubuntu-21.04, ubuntu-21.10, ubuntu-22.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper make

      - name: Build deb package
        run: |
          cd argocomplete
          dpkg-buildpackage -us -uc -b

      - name: Upload deb package
        uses: actions/upload-artifact@v2
        with:
          name: argocomplete-deb
          path: ./*.deb
